version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - elijah-network

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mqtt-data:/mosquitto/data
    restart: always
    networks:
      - elijah-network

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    depends_on:
      - mqtt  
    devices:
      - "/dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_6c77c37787c2ef118a9fc6138148b910-if00-port0:/dev/ttyUSB0"
    ports:
      - "8080:8080"
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Amsterdam
      - MQTT_SERVER=mqtt://mqtt:1883  
    networks:
      - elijah-network

  elijah:
    build:
      context: .
      dockerfile: Elijah.Host/Dockerfile
    container_name: elijah
    depends_on:
      - postgres
      - mqtt
    environment:
      ConnectionStrings__DefaultConnection: ${DEFAULT_CONNECTION}
      MqttConfig__Hostname: mqtt  
      MqttConfig__Port: "1883"
    restart: always
    networks:
      - elijah-network

networks:
  elijah-network:
    driver: bridge

volumes:
  pgdata:
  mqtt-data:
  zigbee2mqtt-data:
